version: '3'
services:
  web:
    volumes:
     - ".:/code"
    build:
      context: .
      dockerfile: Dockerfile-start
    ports:
     - "8080:8080"
  test:
    volumes:
     - ".:/code"
    build:
      context: .
      dockerfile: Dockerfile-test
