version: '3.4'
services:
  # build base first (or build all twice)
  base:
    image: lilengine:base
    volumes:
      - .:/code
    build: 
      context: .
      dockerfile: Dockerfile-base
  web:
    image: lilengine:web
    depends_on:
      - base
    volumes:
      - .:/code
    build: 
      context: .
      dockerfile: Dockerfile-start
  lint:
    image: lilengine:lint
    depends_on:
      - base
    volumes:
      - .:/code
    build:
      context: .
      dockerfile: Dockerfile-lint
